import { existsSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { allLines, audioPath } from "./lines";

const publicDir = new URL("../../public/", import.meta.url);

// The script and the clips travel together: every line the 御霊 can say has its mp3 in
// public/kitan/voice, generated by scripts/voice/generate.py. A line added without its clip
// fails here, which is the reminder to run the generator.
describe("voice clips", () => {
  it("exist for every line in the script", () => {
    const missing: string[] = [];
    for (const { spirit, line } of allLines()) {
      const file = fileURLToPath(new URL(`.${audioPath(spirit, line)}`, publicDir));
      if (!existsSync(file) || statSync(file).size < 1000) missing.push(line.id);
    }
    expect(missing, `run: pnpm voice:lines && pnpm voice:generate`).toEqual([]);
  });
});
